accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import CustomPasswordResetView
from django.contrib.auth.views import PasswordResetConfirmView,PasswordResetDoneView,PasswordResetCompleteView
app_name='accounts'


urlpatterns = [
    
    path('login/',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('signup/',views.signup_view,name='signup'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    
   
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.views import *
app_name='blog'


urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('test',test,name='test'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author')

]

mysite/urls.py
from django.contrib import admin

from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from coming_soon.views import coming_soon
from django.urls import re_path
from django.shortcuts import redirect
from django.views.generic.base import RedirectView







sitemaps = {
    'static': StaticViewSitemap,
    'blog':BlogSitemap
}




urlpatterns = [
    path('coming_soon/', coming_soon, name='coming_soon'),
    re_path(r'^.*$', lambda request: redirect('coming_soon')),
   
    
    path('admin/', admin.site.urls),
    #path('', coming_soon, name='coming_soon'),

    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),   
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    
   
   
    ]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class EmailOrUsernameAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Email or Username')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from accounts.forms import EmailOrUsernameAuthenticationForm
from django.contrib.auth.views import PasswordResetView,PasswordResetView, PasswordResetDoneView
from django.urls import reverse_lazy


class CustomLoginView(LoginView):
    form_class = EmailOrUsernameAuthenticationForm
    template_name = 'accounts/login.html'

def login_view(request):
    # if request.user.is_authenticated:
    #     msg= f'user is authenticated as {request.user.username}'
    # else:
    #     msg='user is not authenticated'   
    if not request.user.is_authenticated:
     
        if request.method == 'POST':
            form=AuthenticationForm(request=request,data=request.POST)
            if form.is_valid():
                username=form.cleaned_data.get('username')
                password=form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')
                
        form= AuthenticationForm() 
        context={'form':form}   
        return render(request,'accounts/login.html',context)
    else:
        return redirect('/')
    
@login_required        
def logout_view(request):
    
    logout(request)
    return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        form=UserCreationForm()    
        context={'form':form}
        return render(request,'accounts/signup.html',context)
    else:
        return redirect('/')
    
from django.contrib.auth.views import PasswordResetView

class CustomPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'    



# Create your views here.

templates/accounts/change-password.html
{% extends 'base.html' %}

{% block title %}Change Password Page{% endblock title %}

{% block content %} 
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'accounts:login' %}">Back</a>
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/accounts/login.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Signin Template for Bootstrap</title>

    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method='post' action="{%url 'accounts:login' %}">

        {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="UserName" class="sr-only">UserName</label>
      <input type="text" name="username" id="UserName" class="form-control" placeholder="UserName" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name='password' id="inputPassword" class="form-control" placeholder="Password" required> 
      <!-- {{form.as_p}} -->
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

templates/accounts/password_reset_done.html
<!-- password_reset_done.html -->

{% extends "base.html" %}

{% block content %}
  <h1>Password reset email sent</h1>
  <p>We have sent you an email with instructions on how to reset your password.</p>
{% endblock %}

templates/accounts/password_reset_email.html
{% autoescape off %}
    <p>Hi {{ user.username }},</p>
    <p>You're receiving this email because you requested a password reset for your user account at {{ site_name }}.</p>
    <p>Please go to the following page and choose a new password:</p>
    <p><a href="{{ password_reset_confirm_url }}">{{ password_reset_confirm_url }}</a></p>
    <p>If you didn't request this reset, please ignore this email. Your password will stay the same.</p>
{% endautoescape %}

templates/accounts/password_reset_form.html
<!-- password_reset_form.html -->

{% extends "base.html" %}

{% block content %}
  <h1>Reset password</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
  </form>
{% endblock %}

templates/accounts/signup.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>SignUp Template for Bootstrap</title>

    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method='post' action="{%url 'accounts:signup' %}">

        {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
       <label for="UserName" class="sr-only">UserName</label>
      <input type="text" name="username" id="UserName" class="form-control" placeholder="UserName" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name='password1' id="inputPassword" class="form-control" placeholder="Password" required>  
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name='password2' id="inputPassword" class="form-control" placeholder="Confirm Password" required>  
      
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>