blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.views import *
app_name='blog'


urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('test',test,name='test'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author')

]

mysite/urls.py
from django.contrib import admin

from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from coming_soon.views import coming_soon
from django.urls import re_path
from django.shortcuts import redirect
from django.views.generic.base import RedirectView







sitemaps = {
    'static': StaticViewSitemap,
    'blog':BlogSitemap
}




urlpatterns = [
    path('coming_soon/', coming_soon, name='coming_soon'),
    re_path(r'^.*$', lambda request: redirect('coming_soon')),
   
    
    path('admin/', admin.site.urls),
    #path('', coming_soon, name='coming_soon'),

    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),   
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    
   
   
    ]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path,include
from website.views import *
app_name='website'



urlpatterns = [
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view, name='contact'),
    path('newsletter',newsletter_view,name='newsletter')
]

website/models.py
from django.db import models



class Contact(models.Model):
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255,blank=True)
    message=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    
    class Meta():
        ordering =['created_date']  
        
        

    def __str__(self):
        return self.name
    
class Newsletter(models.Model):
    email=models.EmailField()  
   
    def __str__(self):
        return self.email  

website/forms.py
from django import forms
from website.models import Newsletter,Contact
from captcha.fields import CaptchaField




class NewsletterForm(forms.ModelForm):
    
    class Meta:
        model=Newsletter
        fields='__all__'

class ContactForm(forms.ModelForm):
    
    def clean_name(self):
        name=self.cleaned_data['name']
        name='unkown'
        return name
    
    captcha = CaptchaField()
    class Meta:
        model=Contact
        fields='__all__' 
        

  
        
     

website/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from website.models import Newsletter,Contact
from website.forms import NewsletterForm,ContactForm
from django.contrib import messages
from django.shortcuts import render


def index_view(request):
    return render(request,'website/index.html')

def about_view(request):
    return render(request,'website/about.html')

def contact_view(request):
    

        
    if request.method =='POST':
        
     
        form=ContactForm(request.POST)
        if form.is_valid():
                                 
            form.save()
            # messages.add_message(request,messages.SUCCESS,'Your messsage is submited successfully')
            
            messages.success(request, "Message sent." )
            return redirect('website:contact')

        else:
            # messages.add_message(request,messages.ERROR,'Your messsage is failed')
            messages.error(request, "Error. Message not sent.")


    form=ContactForm()       
     
    return render(request,'website/contact.html',{'form':form})

def newsletter_view(request): 
    if request.method == 'POST':
        form=NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

templates/website/about.html
{% extends 'base.html' %}
{%load static%}
{% block content%}

<!-- start banner Area -->
<section class="about-banner relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					About Us
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="about.html"> About Us</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 info-left">
				<img class="img-fluid" src="{% static 'img/about/info-img.jpg'%}" alt="">
			</div>
			<div class="col-lg-6 info-right">
				<h6>About Us</h6>
				<h1>Who We Are?</h1>
				<p>
					Here, I focus on a range of items and features that we use in life without giving them a second
					thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
					incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
					ullamco.
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Other issues we can help you with</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o1.jpg'%}" alt="">
					</div>
					<a href="#">
						<h4>Rent a Car</h4>
					</a>
					<p>
						The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o2.jpg'%}" alt="">
					</div>
					<a href="#">
						<h4>Cruise Booking</h4>
					</a>
					<p>
						I was always somebody who felt quite sorry for myself, what I had not got compared.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o3.jpg'%}" alt="">
					</div>
					<a href="#">
						<h4>To Do List</h4>
					</a>
					<p>
						The following article covers a topic that has recently moved to center stage–at least it seems.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o4.jpg'%}" alt="">
					</div>
					<a href="#">
						<h4>Food Features</h4>
					</a>
					<p>
						There are many kinds of narratives and organizing principles. Science is driven by evidence.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End other-issue Area -->

{%endblock%}

templates/website/contact.html
{% extends 'base.html' %}

{%load static%}
{% block content%}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Contact Us
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="contact.html"> Contact Us</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
	<div class="container">
		<div class="row">
			<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
			<div class="col-lg-4 d-flex flex-column address-wrap">
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-home"></span>
					</div>
					<div class="contact-details">
						<h5>Binghamton, New York</h5>
						<p>
							4343 Hinkle Deegan Lake Road
						</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-phone-handset"></span>
					</div>
					<div class="contact-details">
						<h5>00 (958) 9865 562</h5>
						<p>Mon to Fri 9am to 6 pm</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-envelope"></span>
					</div>
					<div class="contact-details">
						<h5>support@colorlib.com</h5>
						<p>Send us your query anytime!</p>
					</div>
				</div>
			</div>
			<div class="col-lg-8">
				<form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
					<div class="row">
						{% csrf_token%}
						 <div class="col-lg-6 form-group">
							<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control"
								required="" type="text">

							<input name="email" placeholder="Enter email address"
								pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
								class="common-input mb-20 form-control" required="" type="email">

							<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control"
								required="" type="text"> 

							 
						</div>
						<div class="col-lg-6 form-group">
							<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'"
								required="" ></textarea>
						</div>
						<div class="col-lg-12">
							<div class='pb-3'>
								{{form.captcha}}
							</div>
							
							<div class="alert-msg" style="text-align: left;"></div>
							<button type="submit" formnovalidate  class="genric-btn primary" style="float: right;">Send Message</button>
						</div>
						
						
						
					</div>
				</form>
			</div>
			<!-- {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
  {% endif %}

  {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
  {% endif %} -->

		</div>
	</div>
</section>
<!-- End contact-page Area -->

{%endblock%}

templates/website/latestpost.html
{%load static%}
{% load website_tags %}


<div class="row">
    <div class="active-recent-blog-carusel">
        {%for post in posts%}
        <div class="single-recent-blog-post item">

            <div class="thumb">
               <a href="{% url 'blog:single' pid=post.id %}"><img class="img-fluid imgblogwebsite" src="{{post.image.url}}" alt="" ></a> 
            </div>
            <div class="details">
                <div class="tags">
                    <ul>
                        <li>
                            <a href="#">Travel</a>
                        </li>
                        <li>
                            <a href="#">Life Style</a>
                        </li>
                    </ul>
                </div>
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h4 class="title">{{post.title}}</h4>
                </a>
                <p>
                    {{post.content|truncatewords:5}}
                </p>
                <h6 class="date">{{post.published_date}}</h6>
            </div>
        </div>
        {%endfor%}
    
        
    </div>
</div>

templates/website/messages.html
<!-- {% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %} -->


<!-- {% for message in messages %}
<div class="popup" onclick="myFunction()">Click me!
    <span class="popuptext" id="myPopup">Popup text...</span>
  </div>
  {% endfor %}
  
  <script>
    // When the user clicks on <div>, open the popup
    function myFunction() {
      var popup = document.getElementById("myPopup");
      popup.classList.toggle("show");
    }
    </script> -->
    {% load static %}

    {% if messages %}
<ul class="messages">
{% for message in messages %}
<li class="{{ message.tags }}">{{ message }}</li>
{% endfor %}
</ul>
{% endif %}

    <li id="message_container" class="{{ message.tags }}">{{ message }}</li>

<script>
var message_ele = document.getElementById("message_container");

setTimeout(function(){ 
message_ele.style.display = "none"; 
}, 10000);
</script>
  
<!-- {% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
          <i class="fas fa-times mr-2"></i>
        {% elif message.tags == 'warning' %}
          <i class="fas fa-exclamation mr-2"></i>
        {% elif message.tags == 'info' %}
          <i class="fas fa-info mr-2"></i>
        {% elif message.tags == 'success' %}
          <i class="fas fa-check mr-2"></i>
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %} -->